# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8mDtFIc0z8ycw7pVP0qiG_RAD3xz-lX
"""

P1 = 100
P2 = 50
P3 = 40
T_B = 150
T_C = P1+P2+P3
if (T_B >= T_C) :
    diff=T_B-T_C
    print(f"Our Budget Cover the items cost , and we have {diff} $ left")
else :
  diff=T_B-T_C
  print(f"Our Budget is less than the cost by {diff} $ ")